In [1]:
import pandas as pd #verileri düzgün şekilde tutabilmek içindir(dataframe içerisinde)
import numpy as np #büyük sayılar ve hesaplama işlemleri için kullanılır
import matplotlib.pyplot as plt #çizim için kullanılır

In [3]:
#çift tırnakta olur tekte
veriler=pd.read_csv('odev_tenis.csv')
#pd.read_csv("veriler.csv")

In [4]:
veriler

outlook  temperature  humidity  windy play
0      sunny           85        85  False   no
1      sunny           80        90   True   no
2   overcast           83        86  False  yes
3      rainy           70        96  False  yes
4      rainy           68        80  False  yes
5      rainy           65        70   True   no
6   overcast           64        65   True  yes
7      sunny           72        95  False   no
8      sunny           69        70  False  yes
9      rainy           75        80  False  yes
10     sunny           75        70   True  yes
11  overcast           72        90   True  yes
12  overcast           81        75  False  yes
13     rainy           71        91   True   no

In [5]:
# tüm verilere LabelEncoding uyguladık
from sklearn import preprocessing
veriler2 = veriler.apply(preprocessing.LabelEncoder().fit_transform)
veriler2

outlook  temperature  humidity  windy  play
0         2           11         4      0     0
1         2            8         6      1     0
2         0           10         5      0     1
3         1            4         9      0     1
4         1            2         3      0     1
5         1            1         1      1     0
6         0            0         0      1     1
7         2            6         8      0     0
8         2            3         1      0     1
9         1            7         3      0     1
10        2            7         1      1     1
11        0            6         6      1     1
12        0            9         2      0     1
13        1            5         7      1     0

In [6]:
# oulook kısmmını aldık içerisinden, one hot encoding yapmak için
c = veriler2.iloc[:, :1]

In [7]:
# outlook kısmına OneHotEncoding yaptık
from sklearn import preprocessing
ohe = preprocessing.OneHotEncoder()
c= ohe.fit_transform(c).toarray()

In [9]:
havadurumu = pd.DataFrame(data=c, index=range(14), columns=['o','r','s'])
sonveriler = pd.concat([havadurumu,veriler.iloc[:,1:3]],axis=1)
sonveriler = pd.concat([veriler2.iloc[:,-2:],sonveriler],axis=1)

sonveriler

windy  play    o    r    s  temperature  humidity
0       0     0  0.0  0.0  1.0           85        85
1       1     0  0.0  0.0  1.0           80        90
2       0     1  1.0  0.0  0.0           83        86
3       0     1  0.0  1.0  0.0           70        96
4       0     1  0.0  1.0  0.0           68        80
5       1     0  0.0  1.0  0.0           65        70
6       1     1  1.0  0.0  0.0           64        65
7       0     0  0.0  0.0  1.0           72        95
8       0     1  0.0  0.0  1.0           69        70
9       0     1  0.0  1.0  0.0           75        80
10      1     1  0.0  0.0  1.0           75        70
11      1     1  1.0  0.0  0.0           72        90
12      0     1  1.0  0.0  0.0           81        75
13      1     0  0.0  1.0  0.0           71        91

In [10]:
# verilerin egitim ve test icin bolunmesi

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(sonveriler.iloc[:,:-1],sonveriler.iloc[:,-1:],test_size=0.33,random_state=0)

In [11]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [12]:
y_pred = regressor.predict(x_test)

In [13]:
y_pred

array([[84.45365573],
       [63.93839954],
       [85.76050662],
       [64.21013241],
       [75.06793322]])

In [14]:
y_test

humidity
8         70
6         65
4         80
11        90
2         86

In [17]:
import statsmodels.api as sm

X = np.append(arr = np.ones((14,1)).astype(int),values=sonveriler.iloc[:,:-1], axis=1)
print(X)

[[ 1.  0.  0.  0.  0.  1. 85.]
 [ 1.  1.  0.  0.  0.  1. 80.]
 [ 1.  0.  1.  1.  0.  0. 83.]
 [ 1.  0.  1.  0.  1.  0. 70.]
 [ 1.  0.  1.  0.  1.  0. 68.]
 [ 1.  1.  0.  0.  1.  0. 65.]
 [ 1.  1.  1.  1.  0.  0. 64.]
 [ 1.  0.  0.  0.  0.  1. 72.]
 [ 1.  0.  1.  0.  0.  1. 69.]
 [ 1.  0.  1.  0.  1.  0. 75.]
 [ 1.  1.  1.  0.  0.  1. 75.]
 [ 1.  1.  1.  1.  0.  0. 72.]
 [ 1.  0.  1.  1.  0.  0. 81.]
 [ 1.  1.  0.  0.  1.  0. 71.]]


In [20]:
X_l = sonveriler.iloc[:,[0,1,2,3,4,5]].values
X_l= np.array(X_l, dtype=float)
model = sm.OLS(sonveriler.iloc[:,-1:],X_l).fit()
print(model.summary())


                            OLS Regression Results                            
Dep. Variable:               humidity   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                 -0.148
Method:                 Least Squares   F-statistic:                    0.6653
Date:                Wed, 03 Jan 2024   Prob (F-statistic):              0.661
Time:                        15:25:13   Log-Likelihood:                -49.542
No. Observations:                  14   AIC:                             111.1
Df Residuals:                       8   BIC:                             114.9
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -4.0286      7.229     -0.557      0.5

c:\Users\zeyne\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\stats\_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [22]:
import statsmodels.api as sm

X = np.append(arr= np.ones((14,1)).astype(int),values=sonveriler.iloc[:,:-1], axis=1)

sonveriler = sonveriler.iloc[:,1:]

X_1 = sonveriler.iloc[:,[0,1,2,3,4]].values
X_1= np.array(X_1, dtype=float)
model = sm.OLS(sonveriler.iloc[:,-1:],X,1).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:               humidity   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                 -0.060
Method:                 Least Squares   F-statistic:                    0.8165
Date:                Wed, 03 Jan 2024   Prob (F-statistic):              0.546
Time:                        15:28:54   Log-Likelihood:                -49.809
No. Observations:                  14   AIC:                             109.6
Df Residuals:                       9   BIC:                             112.8
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         28.4191     28.743      0.989      0.3

c:\Users\zeyne\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\stats\_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [23]:
x_train = x_train.iloc[:,1:]
x_test = x_test.iloc[:,1:]

In [24]:
regressor.fit(x_train,y_train)

y_pred = regressor.predict(x_test)