# 1.Kutuphaneler

In [113]:
import pandas as pd #verileri düzgün şekilde tutabilmek içindir(dataframe içerisinde)
import numpy as np #büyük sayılar ve hesaplama işlemleri için kullanılır
import matplotlib.pyplot as plt #çizim için kullanılır

# Kodlar

# 2.Veri onisleme

In [114]:
#çift tırnakta olur tekte
veriler=pd.read_csv('veriler.csv')
#pd.read_csv("veriler.csv")

In [134]:
#kategorik veriler - encoder: Nominal Ordidal(kategorik) -> Numeric
veriler

ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [135]:
ulke = veriler.iloc[:, 0:1].values
Yas = veriler.iloc[:, :-2]
print(ulke)

[['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']]


In [117]:
from sklearn import preprocessing

In [118]:
le = preprocessing.LabelEncoder()

In [119]:
ulke[:,0] = le.fit_transform(veriler.iloc[:,0])

In [120]:
print(ulke)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [121]:
ohe = preprocessing.OneHotEncoder()

In [122]:
ulke = ohe.fit_transform(ulke).toarray()

In [123]:
#kategorik veriler - encoder: Nominal Ordidal(kategorik) -> Numeric
c = veriler.iloc[:, -1:].values
print(c)

from sklearn import preprocessing

le = preprocessing.LabelEncoder() # encoding categorical labels into numerical values.

c[:, -1] = le.fit_transform(veriler.iloc[:,-1])

print(c)


[['e']
 ['e']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['k']
 ['k']]
[[0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]]


In [124]:
ohe = preprocessing.OneHotEncoder()
c = ohe.fit_transform(c).toarray()
print(c)

[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [125]:
#numpy dizilerin dataframe'e dönüşümü
sonuc = pd.DataFrame(data=ulke, index=range(22), columns=['fr', 'tr', 'us'])
print(sonuc)

     fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0


In [136]:
sonuc2 = pd.DataFrame(data=Yas, index = range(22), columns = ['boy','kilo','yas'])
print(sonuc2)

    boy  kilo  yas
0   130    30  NaN
1   125    36  NaN
2   135    34  NaN
3   133    30  NaN
4   129    38  NaN
5   180    90  NaN
6   190    80  NaN
7   175    90  NaN
8   177    60  NaN
9   185   105  NaN
10  165    55  NaN
11  155    50  NaN
12  160    58  NaN
13  162    59  NaN
14  167    62  NaN
15  174    70  NaN
16  193    90  NaN
17  187    80  NaN
18  183    88  NaN
19  159    40  NaN
20  164    66  NaN
21  166    56  NaN


In [137]:
cinsiyet = veriler.iloc[:,-1].values
print(cinsiyet)

['e' 'e' 'k' 'k' 'e' 'e' 'e' 'e' 'k' 'e' 'k' 'k' 'k' 'k' 'k' 'e' 'e' 'e'
 'e' 'k' 'k' 'k']


In [138]:
sonuc3 = pd.DataFrame(data=c[:,:1], index = range(22), columns=['cinsiyet'])
print(sonuc3)

    cinsiyet
0        1.0
1        1.0
2        0.0
3        0.0
4        1.0
5        1.0
6        1.0
7        1.0
8        0.0
9        1.0
10       0.0
11       0.0
12       0.0
13       0.0
14       0.0
15       1.0
16       1.0
17       1.0
18       1.0
19       0.0
20       0.0
21       0.0


In [139]:
#dataframe birlestirme islemi
s=pd.concat([sonuc,sonuc2], axis=1)
print(s)

     fr   tr   us  boy  kilo  yas
0   0.0  1.0  0.0  130    30  NaN
1   0.0  1.0  0.0  125    36  NaN
2   0.0  1.0  0.0  135    34  NaN
3   0.0  1.0  0.0  133    30  NaN
4   0.0  1.0  0.0  129    38  NaN
5   0.0  1.0  0.0  180    90  NaN
6   0.0  1.0  0.0  190    80  NaN
7   0.0  1.0  0.0  175    90  NaN
8   0.0  1.0  0.0  177    60  NaN
9   0.0  0.0  1.0  185   105  NaN
10  0.0  0.0  1.0  165    55  NaN
11  0.0  0.0  1.0  155    50  NaN
12  0.0  0.0  1.0  160    58  NaN
13  0.0  0.0  1.0  162    59  NaN
14  0.0  0.0  1.0  167    62  NaN
15  1.0  0.0  0.0  174    70  NaN
16  1.0  0.0  0.0  193    90  NaN
17  1.0  0.0  0.0  187    80  NaN
18  1.0  0.0  0.0  183    88  NaN
19  1.0  0.0  0.0  159    40  NaN
20  1.0  0.0  0.0  164    66  NaN
21  1.0  0.0  0.0  166    56  NaN


In [140]:
s2=pd.concat([s,sonuc3], axis=1)
print(s2)

     fr   tr   us  boy  kilo  yas  cinsiyet
0   0.0  1.0  0.0  130    30  NaN       1.0
1   0.0  1.0  0.0  125    36  NaN       1.0
2   0.0  1.0  0.0  135    34  NaN       0.0
3   0.0  1.0  0.0  133    30  NaN       0.0
4   0.0  1.0  0.0  129    38  NaN       1.0
5   0.0  1.0  0.0  180    90  NaN       1.0
6   0.0  1.0  0.0  190    80  NaN       1.0
7   0.0  1.0  0.0  175    90  NaN       1.0
8   0.0  1.0  0.0  177    60  NaN       0.0
9   0.0  0.0  1.0  185   105  NaN       1.0
10  0.0  0.0  1.0  165    55  NaN       0.0
11  0.0  0.0  1.0  155    50  NaN       0.0
12  0.0  0.0  1.0  160    58  NaN       0.0
13  0.0  0.0  1.0  162    59  NaN       0.0
14  0.0  0.0  1.0  167    62  NaN       0.0
15  1.0  0.0  0.0  174    70  NaN       1.0
16  1.0  0.0  0.0  193    90  NaN       1.0
17  1.0  0.0  0.0  187    80  NaN       1.0
18  1.0  0.0  0.0  183    88  NaN       1.0
19  1.0  0.0  0.0  159    40  NaN       0.0
20  1.0  0.0  0.0  164    66  NaN       0.0
21  1.0  0.0  0.0  166    56  Na

In [141]:
#verilerin egitim ve test icin bolunmesi
from sklearn.model_selection import train_test_split

In [142]:
x_train, x_test,y_train,y_test = train_test_split(s,sonuc3,test_size=0.33, random_state=0)
